### ISSUE TITLE
JavaScript Group Project

### ISSUE THREAD

**Issue by Leeoasis** [Leeoasis/JavaScript-Group-Capstone#21]
https://github.com/Leeoasis/JavaScript-Group-Capstone/projects/1

There are two people in our group i.e Leslie and Ismail Munyentwari.

**Comment by leonardodiasb** [comment]
# Required Changes ♻️ ⚠️ 🚦 

Hi @Leeoasis, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Aspects to improve ♻️

- [x] Check the comments under the review.
- [ ] You added the cards to the Kanban board correctly, but you did not assign any student to any of those cards. Kindly assign students A and B to the corresponding cards in the Kanban board as the project required. See the example below:
- 
<img width="362" alt="image" src="https://user-images.githubusercontent.com/61919617/224739444-5228cd56-743e-4fbd-8900-17ba0f2afa75.png">

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gemmen29** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- Descriptive info ✔️ 
- Tasks distributed equally ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
